# fly.toml app configuration file generated for datenow on 2023-08-15T17:50:27+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datenow"
primary_region = "hkg"

[build]
  image = "qblong/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dd2f0rvq1"
  CloudinarySettings__ApiKey="713734898235375"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
